<?php

/**
 * Test class for soapclient.
 * Generated by PHPUnit on 2012-07-16 at 11:16:24.
 */
class soapclientTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var soapclient
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new soapclient;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

}

?>
