<?php

require_once dirname(__FILE__) . '/../../../../../extensions/waste_streams/classes/MWasteStreams.class.php';

/**
 * Test class for MWasteStreams.
 * Generated by PHPUnit on 2012-07-16 at 11:14:57.
 */
class MWasteStreamsTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var MWasteStreams
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new MWasteStreams;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testGetNewObject().
	 */
	public function testGetNewObject() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testValidateWastes().
	 */
	public function testValidateWastes() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testPrepare4mixAdd().
	 */
	public function testPrepare4mixAdd() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCalculateWaste().
	 */
	public function testCalculateWaste() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testPrepareSaveWasteStreams().
	 */
	public function testPrepareSaveWasteStreams() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testPrepareViewMix().
	 */
	public function testPrepareViewMix() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testPrepareViewStorage().
	 */
	public function testPrepareViewStorage() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testPrepareBrowseStorage().
	 */
	public function testPrepareBrowseStorage() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testPrepareAddStorage().
	 */
	public function testPrepareAddStorage() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testPrepareDeleteStorage().
	 */
	public function testPrepareDeleteStorage() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
