<?php

require_once dirname(__FILE__) . '/../../../../modules/mail/mimePart.php';

/**
 * Test class for Mail_mimePart.
 * Generated by PHPUnit on 2012-07-16 at 11:13:40.
 */
class Mail_mimePartTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var Mail_mimePart
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Mail_mimePart;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testEncode().
	 */
	public function testEncode() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testAddSubPart().
	 */
	public function testAddSubPart() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement test_getEncodedData().
	 */
	public function test_getEncodedData() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement test_quotedPrintableEncode().
	 */
	public function test_quotedPrintableEncode() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement test_buildHeaderParam().
	 */
	public function test_buildHeaderParam() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
