<?php

require_once dirname(__FILE__) . '/../../../../../modules/mail/PEAR/Dependency.php';

/**
 * Test class for PEAR_Dependency.
 * Generated by PHPUnit on 2012-07-16 at 11:15:06.
 */
class PEAR_DependencyTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var PEAR_Dependency
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new PEAR_Dependency;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testCallCheckMethod().
	 */
	public function testCallCheckMethod() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCheckPackage().
	 */
	public function testCheckPackage() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCheckPackageUninstall().
	 */
	public function testCheckPackageUninstall() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCheckExtension().
	 */
	public function testCheckExtension() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCheckOS().
	 */
	public function testCheckOS() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCheckPHP().
	 */
	public function testCheckPHP() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCheckProgram().
	 */
	public function testCheckProgram() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCheckSAPI().
	 */
	public function testCheckSAPI() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCheckZend().
	 */
	public function testCheckZend() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSignOperator().
	 */
	public function testSignOperator() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCodeFromRelation().
	 */
	public function testCodeFromRelation() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
