<?php

require_once dirname(__FILE__) . '/../../../../../modules/mail/PEAR/Packager.php';

/**
 * Test class for PEAR_Packager.
 * Generated by PHPUnit on 2012-07-16 at 11:15:07.
 */
class PEAR_PackagerTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var PEAR_Packager
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new PEAR_Packager;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testPackage().
	 */
	public function testPackage() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
