<?php

require_once dirname(__FILE__) . '/../../../../../modules/mail/PEAR/Builder.php';

/**
 * Test class for PEAR_Builder.
 * Generated by PHPUnit on 2012-07-16 at 11:15:10.
 */
class PEAR_BuilderTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var PEAR_Builder
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new PEAR_Builder;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement test_build_win32().
	 */
	public function test_build_win32() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testMsdevCallback().
	 */
	public function testMsdevCallback() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement test_harvestInstDir().
	 */
	public function test_harvestInstDir() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testBuild().
	 */
	public function testBuild() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testPhpizeCallback().
	 */
	public function testPhpizeCallback() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement test_runCommand().
	 */
	public function test_runCommand() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testLog().
	 */
	public function testLog() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
