<?php

require_once dirname(__FILE__) . '/../../../../../modules/mail/PEAR/XMLParser.php';

/**
 * Test class for PEAR_XMLParser.
 * Generated by PHPUnit on 2012-07-16 at 11:15:06.
 */
class PEAR_XMLParserTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var PEAR_XMLParser
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new PEAR_XMLParser;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testGetData().
	 */
	public function testGetData() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testParse().
	 */
	public function testParse() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testStartHandler().
	 */
	public function testStartHandler() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testPostProcess().
	 */
	public function testPostProcess() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testEndHandler().
	 */
	public function testEndHandler() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCdataHandler().
	 */
	public function testCdataHandler() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
