<?php

require_once dirname(__FILE__) . '/../../../../modules/xml2pdf/mc_table.php';

/**
 * Test class for PDF_MC_Table.
 * Generated by PHPUnit on 2012-07-16 at 11:13:35.
 */
class PDF_MC_TableTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var PDF_MC_Table
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new PDF_MC_Table;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testSetWidths().
	 */
	public function testSetWidths() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSetAligns().
	 */
	public function testSetAligns() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testRow().
	 */
	public function testRow() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCheckPageBreak().
	 */
	public function testCheckPageBreak() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testNbLines().
	 */
	public function testNbLines() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
