<?php

require_once dirname(__FILE__) . '/../../../../../extensions/logbook/classes/Logbook.class.php';

/**
 * Test class for Logbook.
 * Generated by PHPUnit on 2012-07-16 at 11:15:01.
 */
class LogbookTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var Logbook
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Logbook;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testGetActionList().
	 */
	public function testGetActionList() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetItemById().
	 */
	public function testGetItemById() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testLogbookAutocomplete().
	 */
	public function testLogbookAutocomplete() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testLogbookSeach().
	 */
	public function testLogbookSeach() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCountLogbookRecords().
	 */
	public function testCountLogbookRecords() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
