#!/usr/bin/env php
<?php
// app/console
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Command\ListCommand;
use Symfony\Component\Console\Command\GreetCommand;
use VWM\Apps\Reminder\Console\Command\ReminderCommand;

$site_path = dirname(__FILE__).DIRECTORY_SEPARATOR.'..'.DIRECTORY_SEPARATOR;
define ('site_path', $site_path);

require($site_path.'config/constants.php');
require_once ($site_path.'modules/xnyo/xnyo.class.php');

//	Include Class Autoloader
//require $site_path.'../vendor/autoload.php';
$files = array(
  $site_path . '../vendor/autoload.php',
);

$found = false;
foreach ($files as $file) {
    if (file_exists($file)) {
        require $file;
        $found = true;
        break;
    }
}

if (!$found) {
    die(
      'You need to set up the project dependencies using the following commands:' . PHP_EOL .
      'curl -s http://getcomposer.org/installer | php' . PHP_EOL .
      'php composer.phar install' . PHP_EOL
    );
}

$xnyo = new Xnyo();
$xnyo->database_type = DB_TYPE;
$xnyo->db_host = DB_HOST;
$xnyo->db_user = DB_USER;
$xnyo->db_passwd = DB_PASS;
$xnyo->start();

$GLOBALS["db"]->select_db(DB_NAME);
VOCApp::getInstance()->setDB($GLOBALS["db"]);

$application = new Application();
$application->add(new ReminderCommand);
$application->run();