<?php

require_once dirname(__FILE__) . '/../../../../../extensions/reduction/classes/ReductionScheme.class.php';

/**
 * Test class for ReductionScheme.
 * Generated by PHPUnit on 2012-07-16 at 11:14:34.
 */
class ReductionSchemeTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var ReductionScheme
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new ReductionScheme;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testGetAREfactor().
	 */
	public function testGetAREfactor() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetTargetEmissionFactor().
	 */
	public function testGetTargetEmissionFactor() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testLoadFactors().
	 */
	public function testLoadFactors() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSetFactors().
	 */
	public function testSetFactors() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCalculateReduction().
	 */
	public function testCalculateReduction() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetReductionScheme().
	 */
	public function testGetReductionScheme() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetBeginDate().
	 */
	public function testGetBeginDate() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
