<?php

require_once dirname(__FILE__) . '/../../../../../extensions/reduction/classes/SolventManagement.class.php';

/**
 * Test class for SolventManagement.
 * Generated by PHPUnit on 2012-07-16 at 11:14:35.
 */
class SolventManagementTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var SolventManagement
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new SolventManagement;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testGetTotalInput().
	 */
	public function testGetTotalInput() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetMonthlyOutputs().
	 */
	public function testGetMonthlyOutputs() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetQuarterlyOutputs().
	 */
	public function testGetQuarterlyOutputs() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetSemiAnnualyOutputs().
	 */
	public function testGetSemiAnnualyOutputs() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetAnnualyOutputs().
	 */
	public function testGetAnnualyOutputs() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testIniOutputNames().
	 */
	public function testIniOutputNames() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCalculateConsumption().
	 */
	public function testCalculateConsumption() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCalculateFugitiveEmission().
	 */
	public function testCalculateFugitiveEmission() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCalculateAnnualActualSolventEmission().
	 */
	public function testCalculateAnnualActualSolventEmission() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSave().
	 */
	public function testSave() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetBeginDate().
	 */
	public function testGetBeginDate() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetLastUseDate().
	 */
	public function testGetLastUseDate() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetAnnualActualSolventEmissionList().
	 */
	public function testGetAnnualActualSolventEmissionList() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
