<?php

require_once dirname(__FILE__) . '/../../../../modules/classes/AJAXResponse.class.php';

/**
 * Test class for AJAXResponse.
 * Generated by PHPUnit on 2012-07-16 at 11:13:45.
 */
class AJAXResponseTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var AJAXResponse
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new AJAXResponse;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testSetSuccess().
	 */
	public function testSetSuccess() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSetMessage().
	 */
	public function testSetMessage() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testIsSuccess().
	 */
	public function testIsSuccess() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetMessage().
	 */
	public function testGetMessage() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testResponse().
	 */
	public function testResponse() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
