<?php

require_once dirname(__FILE__) . '/../../../../modules/classes/Apmethod.class.php';

/**
 * Test class for Apmethod.
 * Generated by PHPUnit on 2012-07-16 at 11:13:54.
 */
class ApmethodTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var Apmethod
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Apmethod;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testGetApmethodList().
	 */
	public function testGetApmethodList() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetApmethodDetails().
	 */
	public function testGetApmethodDetails() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetDefaultApmethodlist().
	 */
	public function testGetDefaultApmethodlist() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetDefaultApmethodDescriptions().
	 */
	public function testGetDefaultApmethodDescriptions() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSetDefaultAPMethodlist().
	 */
	public function testSetDefaultAPMethodlist() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSetApmethodDetails().
	 */
	public function testSetApmethodDetails() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testAddNewApmethod().
	 */
	public function testAddNewApmethod() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testDeleteApmethod().
	 */
	public function testDeleteApmethod() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testQueryTotalCount().
	 */
	public function testQueryTotalCount() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
