<?php

require_once dirname(__FILE__) . '/../../../../modules/classes/BookmarksManager.class.php';

/**
 * Test class for BookmarksManager.
 * Generated by PHPUnit on 2012-07-16 at 11:14:25.
 */
class BookmarksManagerTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var BookmarksManager
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new BookmarksManager;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testGetBookmark().
	 */
	public function testGetBookmark() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetBookmarkStats().
	 */
	public function testGetBookmarkStats() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testUsers2bookmarks().
	 */
	public function testUsers2bookmarks() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetBookmarksList().
	 */
	public function testGetBookmarksList() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetOriginSupplier().
	 */
	public function testGetOriginSupplier() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetAllSuppliersByOrigin().
	 */
	public function testGetAllSuppliersByOrigin() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetBookmarksListSupplier().
	 */
	public function testGetBookmarksListSupplier() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetCountSupplier().
	 */
	public function testGetCountSupplier() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testDeleteBookmarks().
	 */
	public function testDeleteBookmarks() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetCount().
	 */
	public function testGetCount() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testUpdateType().
	 */
	public function testUpdateType() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
