<?php

require_once dirname(__FILE__) . '/../../../../modules/classes/bulkUploader4PFP.class.php';

/**
 * Test class for bulkUploader4PFP.
 * Generated by PHPUnit on 2012-07-16 at 11:13:56.
 */
class bulkUploader4PFPTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var bulkUploader4PFP
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new bulkUploader4PFP;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testIsRangeRatio().
	 */
	public function testIsRangeRatio() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSplitRangeRatio().
	 */
	public function testSplitRangeRatio() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testIsRtuOrRtsRatio().
	 */
	public function testIsRtuOrRtsRatio() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
