<?php

require_once dirname(__FILE__) . '/../../../../modules/classes/bulkUploader4GOM.class.php';

/**
 * Test class for bulkUploader4GOM.
 * Generated by PHPUnit on 2012-07-16 at 11:14:03.
 */
class bulkUploader4GOMTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var bulkUploader4GOM
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new bulkUploader4GOM;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

}

?>
