<?php

require_once dirname(__FILE__) . '/../../../../modules/classes/Calculator.class.php';

/**
 * Test class for Calculator.
 * Generated by PHPUnit on 2012-07-16 at 11:13:51.
 */
class CalculatorTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var Calculator
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Calculator;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testCalculateVocNew().
	 */
	public function testCalculateVocNew() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCalculateVocwx().
	 */
	public function testCalculateVocwx() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCalculateVoclx().
	 */
	public function testCalculateVoclx() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
