<?php

require_once dirname(__FILE__) . '/../../../../modules/classes/CalendarManager.class.php';

/**
 * Test class for CalendarManager.
 * Generated by PHPUnit on 2012-07-16 at 11:14:05.
 */
class CalendarManagerTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var CalendarManager
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new CalendarManager;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testGetEvents().
	 */
	public function testGetEvents() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetCategory().
	 */
	public function testGetCategory() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
