<?php

require_once dirname(__FILE__) . '/../../../../modules/classes/ComponentProperties.class.php';

/**
 * Test class for ComponentProperties.
 * Generated by PHPUnit on 2012-07-16 at 11:13:59.
 */
class ComponentPropertiesTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var ComponentProperties
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new ComponentProperties;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

}

?>
