<?php

require_once dirname(__FILE__) . '/../../../../modules/classes/DbCacheDependency.class.php';

/**
 * Test class for DbCacheDependency.
 * Generated by PHPUnit on 2012-07-16 at 11:14:27.
 */
class DbCacheDependencyTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var DbCacheDependency
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new DbCacheDependency;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testEvaluateDependency().
	 */
	public function testEvaluateDependency() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testHasChanged().
	 */
	public function testHasChanged() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
