<?php

require_once dirname(__FILE__) . '/../../../../modules/classes/Debug.class.php';

/**
 * Test class for Debug.
 * Generated by PHPUnit on 2012-07-16 at 11:14:06.
 */
class DebugTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var Debug
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Debug;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testPrintMicrotime().
	 */
	public function testPrintMicrotime() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
