<?php

require_once dirname(__FILE__) . '/../../../../modules/classes/EmailNotifications.class.php';

/**
 * Test class for EmailNotifications.
 * Generated by PHPUnit on 2012-07-16 at 11:13:53.
 */
class EmailNotificationsTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var EmailNotifications
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new EmailNotifications;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testGetLimits2Notify().
	 */
	public function testGetLimits2Notify() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetAllLimits().
	 */
	public function testGetAllLimits() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSaveTime().
	 */
	public function testSaveTime() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetLimitsListByUser().
	 */
	public function testGetLimitsListByUser() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetUsersListByLimitType().
	 */
	public function testGetUsersListByLimitType() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCheckLimits().
	 */
	public function testCheckLimits() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSendNotify().
	 */
	public function testSendNotify() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSaveLimits2User().
	 */
	public function testSaveLimits2User() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCheckPeriodicNotifiers().
	 */
	public function testCheckPeriodicNotifiers() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
