<?php

require_once dirname(__FILE__) . '/../../../../modules/classes/EmissionLog.class.php';

/**
 * Test class for EmissionLog.
 * Generated by PHPUnit on 2012-07-16 at 11:13:46.
 */
class EmissionLogTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var EmissionLog
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new EmissionLog;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testGetEmissionLog().
	 */
	public function testGetEmissionLog() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetNoxEmissionLog().
	 */
	public function testGetNoxEmissionLog() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
