<?php

require_once dirname(__FILE__) . '/../../../../modules/classes/EquipmentProperties.class.php';

/**
 * Test class for EquipmentProperties.
 * Generated by PHPUnit on 2012-07-16 at 11:13:49.
 */
class EquipmentPropertiesTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var EquipmentProperties
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new EquipmentProperties;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testSetTrackTowardsDepartment().
	 */
	public function testSetTrackTowardsDepartment() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSetTrackTowardsFacility().
	 */
	public function testSetTrackTowardsFacility() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSetYearlyLimit().
	 */
	public function testSetYearlyLimit() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSetQuarterlyLimit().
	 */
	public function testSetQuarterlyLimit() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSetDailyLimit().
	 */
	public function testSetDailyLimit() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetYearlyLimit().
	 */
	public function testGetYearlyLimit() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetQuarterlyLimit().
	 */
	public function testGetQuarterlyLimit() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetDailyLimit().
	 */
	public function testGetDailyLimit() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetDate().
	 */
	public function testGetDate() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testIsTrackedTowardsDepartment().
	 */
	public function testIsTrackedTowardsDepartment() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testIsTrackedTowardsFacility().
	 */
	public function testIsTrackedTowardsFacility() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testHaveYearlyLimit().
	 */
	public function testHaveYearlyLimit() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testHaveQuarterlyLimit().
	 */
	public function testHaveQuarterlyLimit() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testHaveDailyLimit().
	 */
	public function testHaveDailyLimit() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testIsExpired().
	 */
	public function testIsExpired() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testIsPreExpired().
	 */
	public function testIsPreExpired() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
