<?php

require_once dirname(__FILE__) . '/../../../../modules/classes/FacilityProperties.class.php';

/**
 * Test class for FacilityProperties.
 * Generated by PHPUnit on 2012-07-16 at 11:14:07.
 */
class FacilityPropertiesTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var FacilityProperties
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new FacilityProperties;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testGetMonthlyLimit().
	 */
	public function testGetMonthlyLimit() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetMonthlyNoxLimit().
	 */
	public function testGetMonthlyNoxLimit() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetCompanyID().
	 */
	public function testGetCompanyID() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetFacilityID().
	 */
	public function testGetFacilityID() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetAnnualLimit().
	 */
	public function testGetAnnualLimit() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetAnnualUsage().
	 */
	public function testGetAnnualUsage() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
