<?php

require_once dirname(__FILE__) . '/../../../../modules/classes/Hover.class.php';

/**
 * Test class for Hover.
 * Generated by PHPUnit on 2012-07-16 at 11:13:44.
 */
class HoverTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var Hover
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Hover;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testMixValid().
	 */
	public function testMixValid() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testMixPreExpired().
	 */
	public function testMixPreExpired() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testMixInvalid().
	 */
	public function testMixInvalid() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testEquipmentValid().
	 */
	public function testEquipmentValid() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testEquipmentPreExpired().
	 */
	public function testEquipmentPreExpired() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testEquipmentExpired().
	 */
	public function testEquipmentExpired() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
