<?php

require_once dirname(__FILE__) . '/../../../../modules/classes/HTMLBuilder.class.php';

/**
 * Test class for HTMLBuilder.
 * Generated by PHPUnit on 2012-07-16 at 11:14:14.
 */
class HTMLBuilderTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var HTMLBuilder
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new HTMLBuilder;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

}

?>
