<?php

require_once dirname(__FILE__) . '/../../../../modules/classes/InstallTables.class.php';

/**
 * Test class for InstallTables.
 * Generated by PHPUnit on 2012-07-16 at 11:14:21.
 */
class InstallTablesTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var InstallTables
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new InstallTables;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testCreateAllTables().
	 */
	public function testCreateAllTables() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateLimit2userTable().
	 */
	public function testCreateLimit2userTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateLimitesTable().
	 */
	public function testCreateLimitesTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateNotifytimeTable().
	 */
	public function testCreateNotifytimeTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateModuleTable().
	 */
	public function testCreateModuleTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateChemicalclassTable().
	 */
	public function testCreateChemicalclassTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testInsertIntoChemicalclassTable().
	 */
	public function testInsertIntoChemicalclassTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateProduct2chemicalclassTable().
	 */
	public function testCreateProduct2chemicalclassTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateProduct2companyTable().
	 */
	public function testCreateProduct2companyTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateTrashbinTable().
	 */
	public function testCreateTrashbinTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateCompanyTable().
	 */
	public function testCreateCompanyTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateFacilityTable().
	 */
	public function testCreateFacilityTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateDepartmentTable().
	 */
	public function testCreateDepartmentTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateUserTable().
	 */
	public function testCreateUserTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateCountryTable().
	 */
	public function testCreateCountryTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testInsertIntoCountryTable().
	 */
	public function testInsertIntoCountryTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateStateTable().
	 */
	public function testCreateStateTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testInsertIntoStateTable().
	 */
	public function testInsertIntoStateTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateEquipmentTable().
	 */
	public function testCreateEquipmentTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateProductTable().
	 */
	public function testCreateProductTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateComponentTable().
	 */
	public function testCreateComponentTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateDensityTable().
	 */
	public function testCreateDensityTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testInsertIntoDensityTable().
	 */
	public function testInsertIntoDensityTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateUnittypeTable().
	 */
	public function testCreateUnittypeTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testInsertIntoUnittypeTable().
	 */
	public function testInsertIntoUnittypeTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateRuleTable().
	 */
	public function testCreateRuleTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateCoatTable().
	 */
	public function testCreateCoatTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateSubstrateTable().
	 */
	public function testCreateSubstrateTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateApmethodTable().
	 */
	public function testCreateApmethodTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateSupplierTable().
	 */
	public function testCreateSupplierTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateTypeTable().
	 */
	public function testCreateTypeTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testInsertIntoTypeTable().
	 */
	public function testInsertIntoTypeTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateProductgroupTable().
	 */
	public function testCreateProductgroupTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateMixTable().
	 */
	public function testCreateMixTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateMixgroupTable().
	 */
	public function testCreateMixgroupTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateComponentsgroupTable().
	 */
	public function testCreateComponentsgroupTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateAgencyTable().
	 */
	public function testCreateAgencyTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateAgencybelongTable().
	 */
	public function testCreateAgencybelongTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateHazardousclassTable().
	 */
	public function testCreateHazardousclassTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateGcglistTable().
	 */
	public function testCreateGcglistTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateIssueTable().
	 */
	public function testCreateIssueTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateSelectedruleslistTable().
	 */
	public function testCreateSelectedruleslistTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateAccessoryTable().
	 */
	public function testCreateAccessoryTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateDefaultTable().
	 */
	public function testCreateDefaultTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateUnitclassTable().
	 */
	public function testCreateUnitclassTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testInsertIntoUnitclassTable().
	 */
	public function testInsertIntoUnitclassTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateWasteTable().
	 */
	public function testCreateWasteTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateVpsbillingTable().
	 */
	public function testCreateVpsbillingTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateVpsconfigTable().
	 */
	public function testCreateVpsconfigTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateVpscustomerTable().
	 */
	public function testCreateVpscustomerTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateVpscustomerlimitTable().
	 */
	public function testCreateVpscustomerlimitTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateVpsdeactivationTable().
	 */
	public function testCreateVpsdeactivationTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateVpsdefinedbprequestTable().
	 */
	public function testCreateVpsdefinedbprequestTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateVpsinvoiceTable().
	 */
	public function testCreateVpsinvoiceTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateVpslimitTable().
	 */
	public function testCreateVpslimitTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateVpslimitpriceTable().
	 */
	public function testCreateVpslimitpriceTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateVpsnotificationscriptTable().
	 */
	public function testCreateVpsnotificationscriptTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateVpspaymentTable().
	 */
	public function testCreateVpspaymentTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateVpsschedulecustomerplanTable().
	 */
	public function testCreateVpsschedulecustomerplanTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateVpsschedulelimitTable().
	 */
	public function testCreateVpsschedulelimitTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateVpsuserTable().
	 */
	public function testCreateVpsuserTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateVpspaymentmethodTable().
	 */
	public function testCreateVpspaymentmethodTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateGaclaclTable().
	 */
	public function testCreateGaclaclTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testInsertIntoGaclaclTable().
	 */
	public function testInsertIntoGaclaclTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateGaclaclsectionsTable().
	 */
	public function testCreateGaclaclsectionsTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testInsertIntoGaclaclsectionsTable().
	 */
	public function testInsertIntoGaclaclsectionsTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateGaclaclseqTable().
	 */
	public function testCreateGaclaclseqTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testInsertIntoGaclaclseqTable().
	 */
	public function testInsertIntoGaclaclseqTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateGaclacoTable().
	 */
	public function testCreateGaclacoTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testInsertIntoGaclacoTable().
	 */
	public function testInsertIntoGaclacoTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateGaclacomapTable().
	 */
	public function testCreateGaclacomapTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testInsertIntoGaclacomapTable().
	 */
	public function testInsertIntoGaclacomapTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateGaclacosectionsTable().
	 */
	public function testCreateGaclacosectionsTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testInsertIntoGaclacosectionsTable().
	 */
	public function testInsertIntoGaclacosectionsTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateGaclacosectionsseqTable().
	 */
	public function testCreateGaclacosectionsseqTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testInsertIntoGaclacosectionsseqTable().
	 */
	public function testInsertIntoGaclacosectionsseqTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateGaclacoseqTable().
	 */
	public function testCreateGaclacoseqTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testInsertIntoGaclacoseqTable().
	 */
	public function testInsertIntoGaclacoseqTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateGaclaroTable().
	 */
	public function testCreateGaclaroTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateGaclarogroupsTable().
	 */
	public function testCreateGaclarogroupsTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testInsertIntoGaclarogroupsTable().
	 */
	public function testInsertIntoGaclarogroupsTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateGaclarogroupsidseqTable().
	 */
	public function testCreateGaclarogroupsidseqTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testInsertIntoGaclarogroupsidseqTable().
	 */
	public function testInsertIntoGaclarogroupsidseqTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateGaclarogroupsmapTable().
	 */
	public function testCreateGaclarogroupsmapTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testInsertIntoGaclarogroupsmapTable().
	 */
	public function testInsertIntoGaclarogroupsmapTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateGaclaromapTable().
	 */
	public function testCreateGaclaromapTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateGaclarosectionsTable().
	 */
	public function testCreateGaclarosectionsTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testInsertIntoGaclarosectionsTable().
	 */
	public function testInsertIntoGaclarosectionsTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateGaclarosectionsseqTable().
	 */
	public function testCreateGaclarosectionsseqTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testInsertIntoGaclarosectionsseqTable().
	 */
	public function testInsertIntoGaclarosectionsseqTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateGaclaroseqTable().
	 */
	public function testCreateGaclaroseqTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testInsertIntoGaclaroseqTable().
	 */
	public function testInsertIntoGaclaroseqTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateGaclaxoTable().
	 */
	public function testCreateGaclaxoTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testInsertIntoGaclaxoTable().
	 */
	public function testInsertIntoGaclaxoTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateGaclaxogroupsTable().
	 */
	public function testCreateGaclaxogroupsTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateGaclaxogroupsmapTable().
	 */
	public function testCreateGaclaxogroupsmapTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateGaclaxomapTable().
	 */
	public function testCreateGaclaxomapTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testInsertIntoGaclaxomapTable().
	 */
	public function testInsertIntoGaclaxomapTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateGaclaxosectionsTable().
	 */
	public function testCreateGaclaxosectionsTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testInsertIntoGaclaxosectionsTable().
	 */
	public function testInsertIntoGaclaxosectionsTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateGaclaxosectionsseqTable().
	 */
	public function testCreateGaclaxosectionsseqTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testInsertIntoGaclaxosectionsseqTable().
	 */
	public function testInsertIntoGaclaxosectionsseqTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateGaclaxoseqTable().
	 */
	public function testCreateGaclaxoseqTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testInsertIntoGaclaxoseqTable().
	 */
	public function testInsertIntoGaclaxoseqTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateGaclgroupsaromapTable().
	 */
	public function testCreateGaclgroupsaromapTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateGaclgroupsaxomapTable().
	 */
	public function testCreateGaclgroupsaxomapTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateGaclphpgaclTable().
	 */
	public function testCreateGaclphpgaclTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testInsertIntoGaclphpgaclTable().
	 */
	public function testInsertIntoGaclphpgaclTable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
