<?php

require_once dirname(__FILE__) . '/../../../../modules/classes/Invoice.class.php';

/**
 * Test class for Invoice.
 * Generated by PHPUnit on 2012-07-16 at 11:14:13.
 */
class InvoiceTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var Invoice
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Invoice;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testSetPayment().
	 */
	public function testSetPayment() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateMultiInvoiceForNewCustomer().
	 */
	public function testCreateMultiInvoiceForNewCustomer() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateInvoiceForModule().
	 */
	public function testCreateInvoiceForModule() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateInvoiceForModuleOld().
	 */
	public function testCreateInvoiceForModuleOld() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateInvoiceItemForBilling().
	 */
	public function testCreateInvoiceItemForBilling() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateInvoiceForBilling().
	 */
	public function testCreateInvoiceForBilling() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetDatesForCustomerList().
	 */
	public function testGetDatesForCustomerList() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateInvoiceForLimit().
	 */
	public function testCreateInvoiceForLimit() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCreateCustomInvoice().
	 */
	public function testCreateCustomInvoice() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testUpdateInvoice().
	 */
	public function testUpdateInvoice() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetInvoiceItemsDetails().
	 */
	public function testGetInvoiceItemsDetails() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetInvoiceDetails().
	 */
	public function testGetInvoiceDetails() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetCurrentInvoiceForModule().
	 */
	public function testGetCurrentInvoiceForModule() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetCurrentOrFutureInvoiceForModule().
	 */
	public function testGetCurrentOrFutureInvoiceForModule() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetInvoiceForModuleByStartDate().
	 */
	public function testGetInvoiceForModuleByStartDate() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetModuleIDByBillingModuleID().
	 */
	public function testGetModuleIDByBillingModuleID() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetInvoiceIDByBillingModuleID().
	 */
	public function testGetInvoiceIDByBillingModuleID() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetInvoiceDetailsByBillingModuleID().
	 */
	public function testGetInvoiceDetailsByBillingModuleID() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testIsModuleInMultiinvoice().
	 */
	public function testIsModuleInMultiinvoice() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetCurrentInvoice().
	 */
	public function testGetCurrentInvoice() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetLastInvoice().
	 */
	public function testGetLastInvoice() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetAllInvoicesList().
	 */
	public function testGetAllInvoicesList() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetPaidInvoicesList().
	 */
	public function testGetPaidInvoicesList() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetDueInvoicesList().
	 */
	public function testGetDueInvoicesList() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetCanceledInvoicesList().
	 */
	public function testGetCanceledInvoicesList() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetDiscount().
	 */
	public function testGetDiscount() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetBalance().
	 */
	public function testGetBalance() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetModuleInvoiceWhenTrialPeriod().
	 */
	public function testGetModuleInvoiceWhenTrialPeriod() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetInvoiceWhenTrialPeriod().
	 */
	public function testGetInvoiceWhenTrialPeriod() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetModuleInvoiceForFuturePeriod().
	 */
	public function testGetModuleInvoiceForFuturePeriod() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetInvoiceForFuturePeriod().
	 */
	public function testGetInvoiceForFuturePeriod() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testManualBalanceChange().
	 */
	public function testManualBalanceChange() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testRestoreInvoice().
	 */
	public function testRestoreInvoice() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testChangeInvoiceStatus().
	 */
	public function testChangeInvoiceStatus() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCancelInvoice().
	 */
	public function testCancelInvoice() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetCustomDueInvoices().
	 */
	public function testGetCustomDueInvoices() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testRestoreDueCustomInvoices().
	 */
	public function testRestoreDueCustomInvoices() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCalculateTotal().
	 */
	public function testCalculateTotal() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetInvoiceStatusList().
	 */
	public function testGetInvoiceStatusList() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetInvoiceStatusListNew().
	 */
	public function testGetInvoiceStatusListNew() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testPayInvoiceFromBalance().
	 */
	public function testPayInvoiceFromBalance() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testPartialRefund().
	 */
	public function testPartialRefund() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
