<?php

require_once dirname(__FILE__) . '/../../../../modules/classes/Issue.class.php';

/**
 * Test class for Issue.
 * Generated by PHPUnit on 2012-07-16 at 11:13:52.
 */
class IssueTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var Issue
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Issue;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testAddIssue().
	 */
	public function testAddIssue() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetIssuesList().
	 */
	public function testGetIssuesList() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetIssueDetails().
	 */
	public function testGetIssueDetails() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testUpdateIssueDetails().
	 */
	public function testUpdateIssueDetails() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testDeleteIssue().
	 */
	public function testDeleteIssue() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
