<?php

require_once dirname(__FILE__) . '/../../../../modules/classes/Localization.class.php';

/**
 * Test class for Localization.
 * Generated by PHPUnit on 2012-07-16 at 11:14:22.
 */
class LocalizationTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var Localization
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Localization;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testParseXML().
	 */
	public function testParseXML() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSetText().
	 */
	public function testSetText() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testZamusorit().
	 */
	public function testZamusorit() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
