<?php

require_once dirname(__FILE__) . '/../../../../modules/classes/MixManager.class.php';

/**
 * Test class for MixManager.
 * Generated by PHPUnit on 2012-07-16 at 11:13:51.
 */
class MixManagerTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var MixManager
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new MixManager;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testCountMixes().
	 */
	public function testCountMixes() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCountMixesInFacility().
	 */
	public function testCountMixesInFacility() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetMixList().
	 */
	public function testGetMixList() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetMixListInFacility().
	 */
	public function testGetMixListInFacility() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testFillProductsUnitTypes().
	 */
	public function testFillProductsUnitTypes() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testDeleteMixList().
	 */
	public function testDeleteMixList() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
