<?php

require_once dirname(__FILE__) . '/../../../../modules/classes/MixValidator.class.php';

/**
 * Test class for MixValidator.
 * Generated by PHPUnit on 2012-07-16 at 11:14:02.
 */
class MixValidatorTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var MixValidator
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new MixValidator;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testIsValidMix().
	 */
	public function testIsValidMix() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
