<?php

require_once dirname(__FILE__) . '/../../../../modules/classes/MixValidatorResponse.class.php';

/**
 * Test class for MixValidatorResponse.
 * Generated by PHPUnit on 2012-07-16 at 11:13:53.
 */
class MixValidatorResponseTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var MixValidatorResponse
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new MixValidatorResponse;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testSetExpired().
	 */
	public function testSetExpired() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSetPreExpired().
	 */
	public function testSetPreExpired() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSetFacilityLimitExcess().
	 */
	public function testSetFacilityLimitExcess() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSetDepartmentLimitExcess().
	 */
	public function testSetDepartmentLimitExcess() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSetYearlyLimitExcess().
	 */
	public function testSetYearlyLimitExcess() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSetQuarterlyLimitExcess().
	 */
	public function testSetQuarterlyLimitExcess() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSetDailyLimitExcess().
	 */
	public function testSetDailyLimitExcess() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSetValidationStatus().
	 */
	public function testSetValidationStatus() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testIsValid().
	 */
	public function testIsValid() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testIsExpired().
	 */
	public function testIsExpired() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testIsPreExpired().
	 */
	public function testIsPreExpired() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testIsSomeLimitExceeded().
	 */
	public function testIsSomeLimitExceeded() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testIsFacilityLimitExceeded().
	 */
	public function testIsFacilityLimitExceeded() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testIsDepartmentLimitExceeded().
	 */
	public function testIsDepartmentLimitExceeded() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testIsYearlyLimitExceeded().
	 */
	public function testIsYearlyLimitExceeded() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testIsQuarterlyLimitExceeded().
	 */
	public function testIsQuarterlyLimitExceeded() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testIsDailyLimitExceeded().
	 */
	public function testIsDailyLimitExceeded() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSetFacilityAnnualLimitExceeded().
	 */
	public function testSetFacilityAnnualLimitExceeded() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSetDepartmentAnnualLimitExceeded().
	 */
	public function testSetDepartmentAnnualLimitExceeded() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetFacilityAnnualLimitExceeded().
	 */
	public function testGetFacilityAnnualLimitExceeded() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetDepartmentAnnualLimitExceeded().
	 */
	public function testGetDepartmentAnnualLimitExceeded() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testPrintResult().
	 */
	public function testPrintResult() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
