<?php

require_once dirname(__FILE__) . '/../../../../modules/classes/Module.class.php';

/**
 * Test class for Module.
 * Generated by PHPUnit on 2012-07-16 at 11:13:42.
 */
class ModuleTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var Module
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Module;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testGetNewObject().
	 */
	public function testGetNewObject() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
