<?php

require_once dirname(__FILE__) . '/../../../../modules/classes/NoxEmissionManager.class.php';

/**
 * Test class for NoxEmissionManager.
 * Generated by PHPUnit on 2012-07-16 at 11:13:44.
 */
class NoxEmissionManagerTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var NoxEmissionManager
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new NoxEmissionManager;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testGetCountNoxByDepartment().
	 */
	public function testGetCountNoxByDepartment() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetCountNoxByFacility().
	 */
	public function testGetCountNoxByFacility() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetCountBurnerByDepartment().
	 */
	public function testGetCountBurnerByDepartment() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetNoxListByDepartment().
	 */
	public function testGetNoxListByDepartment() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetNoxListByFacility().
	 */
	public function testGetNoxListByFacility() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetBurnerListByDepartment().
	 */
	public function testGetBurnerListByDepartment() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetBurnerDetail().
	 */
	public function testGetBurnerDetail() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetLogDataReadable().
	 */
	public function testGetLogDataReadable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testLoggingAutocomplete().
	 */
	public function testLoggingAutocomplete() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSearchLog().
	 */
	public function testSearchLog() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testDeleteNoxEmissionsByID().
	 */
	public function testDeleteNoxEmissionsByID() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetNoxEmissionDetails().
	 */
	public function testGetNoxEmissionDetails() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCalculateNox().
	 */
	public function testCalculateNox() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetBurnerManufacturerList().
	 */
	public function testGetBurnerManufacturerList() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetBurnerManfucaturer().
	 */
	public function testGetBurnerManfucaturer() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetTotalSumNoxByDepartment().
	 */
	public function testGetTotalSumNoxByDepartment() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetCurrentUsageOptimizedByDepartment().
	 */
	public function testGetCurrentUsageOptimizedByDepartment() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
