<?php

require_once dirname(__FILE__) . '/../../../../modules/classes/SL.class.php';

/**
 * Test class for SL.
 * Generated by PHPUnit on 2012-07-16 at 11:14:24.
 */
class SLTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var SL
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new SL;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testGetLocaleConstants().
	 */
	public function testGetLocaleConstants() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetLocaleConstantAsAssociativeArray().
	 */
	public function testGetLocaleConstantAsAssociativeArray() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSetLocaleConstant().
	 */
	public function testSetLocaleConstant() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSL_old().
	 */
	public function testSL_old() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
