<?php

require_once dirname(__FILE__) . '/../../../../modules/classes/Statistics.class.php';

/**
 * Test class for Statistics.
 * Generated by PHPUnit on 2012-07-16 at 11:14:23.
 */
class StatisticsTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var Statistics
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Statistics;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testSave().
	 */
	public function testSave() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testValidate().
	 */
	public function testValidate() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testShow().
	 */
	public function testShow() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
