<?php

require_once dirname(__FILE__) . '/../../../../modules/classes/Substrate.class.php';

/**
 * Test class for Substrate.
 * Generated by PHPUnit on 2012-07-16 at 11:14:24.
 */
class SubstrateTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var Substrate
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Substrate;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testGetSubstrateList().
	 */
	public function testGetSubstrateList() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetSubstrateDetails().
	 */
	public function testGetSubstrateDetails() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSetSubstrateDetails().
	 */
	public function testSetSubstrateDetails() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testAddNewSubstrate().
	 */
	public function testAddNewSubstrate() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testDeleteSubstrate().
	 */
	public function testDeleteSubstrate() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testQueryTotalCount().
	 */
	public function testQueryTotalCount() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
