<?php

require_once dirname(__FILE__) . '/../../../../modules/classes/Unittype.class.php';

/**
 * Test class for Unittype.
 * Generated by PHPUnit on 2012-07-16 at 11:14:22.
 */
class UnittypeTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var Unittype
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Unittype;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testGetUnittypeList().
	 */
	public function testGetUnittypeList() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetUnittypeDetails().
	 */
	public function testGetUnittypeDetails() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetUnittypesDetails().
	 */
	public function testGetUnittypesDetails() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSetUnittypeDetails().
	 */
	public function testSetUnittypeDetails() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testAddNewUnittype().
	 */
	public function testAddNewUnittype() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testDeleteUnittype().
	 */
	public function testDeleteUnittype() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetUnittypeListDefault().
	 */
	public function testGetUnittypeListDefault() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetUnittypeClass().
	 */
	public function testGetUnittypeClass() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetClassesOfUnits().
	 */
	public function testGetClassesOfUnits() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetDefaultUnitTypelist().
	 */
	public function testGetDefaultUnitTypelist() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSetDefaultUnitTypelist().
	 */
	public function testSetDefaultUnitTypelist() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetUnitTypeExist().
	 */
	public function testGetUnitTypeExist() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetAllClassesOfUnitTypes().
	 */
	public function testGetAllClassesOfUnitTypes() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetUnittypeListDefaultByCompanyId().
	 */
	public function testGetUnittypeListDefaultByCompanyId() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetNameByID().
	 */
	public function testGetNameByID() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetDescriptionByID().
	 */
	public function testGetDescriptionByID() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testIsWeightOrVolume().
	 */
	public function testIsWeightOrVolume() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetUnittypListFromClassOfUnittypeID().
	 */
	public function testGetUnittypListFromClassOfUnittypeID() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetUnittypeListByCategory().
	 */
	public function testGetUnittypeListByCategory() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetAllTypesByCategory().
	 */
	public function testGetAllTypesByCategory() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testInsertOtherUnitType().
	 */
	public function testInsertOtherUnitType() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetUnittypeByName().
	 */
	public function testGetUnittypeByName() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
