<?php

require_once dirname(__FILE__) . '/../../../../modules/classes/UserLoggingManager.class.php';

/**
 * Test class for UserLoggingManager.
 * Generated by PHPUnit on 2012-07-16 at 11:13:43.
 */
class UserLoggingManagerTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var UserLoggingManager
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new UserLoggingManager;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testGetCountLogs().
	 */
	public function testGetCountLogs() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testMakeLog().
	 */
	public function testMakeLog() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetAllLogs().
	 */
	public function testGetAllLogs() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetLogDetail().
	 */
	public function testGetLogDetail() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetLogDataReadable().
	 */
	public function testGetLogDataReadable() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testLoggingAutocomplete().
	 */
	public function testLoggingAutocomplete() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSearchLog().
	 */
	public function testSearchLog() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
