<?php

require_once dirname(__FILE__) . '/../../../../modules/classes/VOC2VPS.class.php';

/**
 * Test class for VOC2VPS.
 * Generated by PHPUnit on 2012-07-16 at 11:14:22.
 */
class VOC2VPSTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var VOC2VPS
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new VOC2VPS;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testLoadConfigs().
	 */
	public function testLoadConfigs() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetCustomerDetails().
	 */
	public function testGetCustomerDetails() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetCustomerLimits().
	 */
	public function testGetCustomerLimits() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSetCustomerLimitByID().
	 */
	public function testSetCustomerLimitByID() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
