<?php

require_once dirname(__FILE__) . '/../../../../modules/classes/VOCApp.class.php';

/**
 * Test class for VOCApp.
 * Generated by PHPUnit on 2012-07-16 at 11:14:25.
 */
class VOCAppTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var VOCApp
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new VOCApp;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testGet_instance().
	 */
	public function testGet_instance() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSetDB().
	 */
	public function testSetDB() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSetUserID().
	 */
	public function testSetUserID() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSetCustomerID().
	 */
	public function testSetCustomerID() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetCustomerID().
	 */
	public function testGetCustomerID() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetDateFormat().
	 */
	public function testGetDateFormat() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetDateFormat_JS().
	 */
	public function testGetDateFormat_JS() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetCache().
	 */
	public function testGetCache() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testPrintDatetimeByCurrentDateformat().
	 */
	public function testPrintDatetimeByCurrentDateformat() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testPrintDatetimeByTimestampInCurrentDateformat().
	 */
	public function testPrintDatetimeByTimestampInCurrentDateformat() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testPrintDatetimeByMySqlDateInCurrentDateformat().
	 */
	public function testPrintDatetimeByMySqlDateInCurrentDateformat() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
