<?php

require_once dirname(__FILE__) . '/../../../../modules/classes/VPS2VOC.class.php';

/**
 * Test class for VPS2VOC.
 * Generated by PHPUnit on 2012-07-16 at 11:14:14.
 */
class VPS2VOCTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var VPS2VOC
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new VPS2VOC;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testGetModuleNameByID().
	 */
	public function testGetModuleNameByID() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetAllModulesDetails().
	 */
	public function testGetAllModulesDetails() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetModules().
	 */
	public function testGetModules() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetCustomerDetails().
	 */
	public function testGetCustomerDetails() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetCurrentEquipmentCount().
	 */
	public function testGetCurrentEquipmentCount() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCheckUserExistence().
	 */
	public function testCheckUserExistence() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetUserID().
	 */
	public function testGetUserID() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetUserDetails().
	 */
	public function testGetUserDetails() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetCompanyLevelUserByCompanyID().
	 */
	public function testGetCompanyLevelUserByCompanyID() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
