<?php

require_once dirname(__FILE__) . '/../../../../modules/classes/VPSBillingManager.class.php';

/**
 * Test class for VPSBillingManager.
 * Generated by PHPUnit on 2012-07-16 at 11:14:08.
 */
class VPSBillingManagerTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var VPSBillingManager
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new VPSBillingManager;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testGetAll().
	 */
	public function testGetAll() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testAddBillingPlan().
	 */
	public function testAddBillingPlan() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
