<?php

require_once dirname(__FILE__) . '/../../../../modules/classes/VPSBilling.class.php';

/**
 * Test class for VPSBilling.
 * Generated by PHPUnit on 2012-07-16 at 11:14:27.
 */
class VPSBillingTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var VPSBilling
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new VPSBilling;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testSetCurrency().
	 */
	public function testSetCurrency() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetCurrency().
	 */
	public function testGetCurrency() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
