<?php

require_once dirname(__FILE__) . '/../../../../modules/classes/VPSCustomerManager.class.php';

/**
 * Test class for VPSCustomerManager.
 * Generated by PHPUnit on 2012-07-16 at 11:14:24.
 */
class VPSCustomerManagerTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var VPSCustomerManager
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new VPSCustomerManager;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testGetCustomerList().
	 */
	public function testGetCustomerList() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
