<?php

require_once dirname(__FILE__) . '/../../../../../modules/phpgacl/adodb/adodb-active-record.inc.php';

/**
 * Test class for ADODB_Active_Table.
 * Generated by PHPUnit on 2012-07-16 at 11:15:13.
 */
class ADODB_Active_TableTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var ADODB_Active_Table
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new ADODB_Active_Table;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

}

?>
