<?php

require_once dirname(__FILE__) . '/../../../../../modules/phpgacl/adodb/adodb-iterator.inc.php';

/**
 * Test class for ADODB_BASE_RS.
 * Generated by PHPUnit on 2012-07-16 at 11:15:15.
 */
class ADODB_BASE_RSTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var ADODB_BASE_RS
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new ADODB_BASE_RS;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testGetIterator().
	 */
	public function testGetIterator() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement test__toString().
	 */
	public function test__toString() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
