<?php

require_once dirname(__FILE__) . '/../../../../../modules/phpgacl/adodb/adodb-exceptions.inc.php';

/**
 * Test class for ADODB_Exception.
 * Generated by PHPUnit on 2012-07-16 at 11:15:34.
 */
class ADODB_ExceptionTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var ADODB_Exception
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new ADODB_Exception;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

}

?>
