<?php

require_once dirname(__FILE__) . '/../../../../../modules/phpgacl/Cache_Lite/Hashed_Cache_Lite.php';

/**
 * Test class for Hashed_Cache_Lite.
 * Generated by PHPUnit on 2012-07-16 at 11:16:39.
 */
class Hashed_Cache_LiteTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var Hashed_Cache_Lite
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new Hashed_Cache_Lite;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement test_setFileName().
	 */
	public function test_setFileName() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement test_create_dir_structure().
	 */
	public function test_create_dir_structure() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement test_remove_dir_structure().
	 */
	public function test_remove_dir_structure() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testClean().
	 */
	public function testClean() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
