<?php

require_once dirname(__FILE__) . '/../../../../../extensions/reports/xml2pdf/xml_parser.php';

/**
 * Test class for xml_parser_handler_class.
 * Generated by PHPUnit on 2012-07-16 at 11:14:47.
 */
class xml_parser_handler_classTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var xml_parser_handler_class
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new xml_parser_handler_class;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testSetError().
	 */
	public function testSetError() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testSetElementData().
	 */
	public function testSetElementData() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testStartElement().
	 */
	public function testStartElement() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testEndElement().
	 */
	public function testEndElement() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testCharacterData().
	 */
	public function testCharacterData() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
