<?php

require_once dirname(__FILE__) . '/../../../../../extensions/reports/classes/PDFBuilder.class.php';

/**
 * Test class for PDFBuilder.
 * Generated by PHPUnit on 2012-07-16 at 11:14:53.
 */
class PDFBuilderTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var PDFBuilder
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new PDFBuilder;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

}

?>
