<?php

require_once dirname(__FILE__) . '/../../../../../extensions/reports/classes/ReportCreator.class.php';

/**
 * Test class for ReportCreator.
 * Generated by PHPUnit on 2012-07-16 at 11:14:54.
 */
class ReportCreatorTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var ReportCreator
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new ReportCreator;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

}

?>
