<?php

require_once dirname(__FILE__) . '/../../../../../extensions/docs/classes/DocContainerItem.class.php';

/**
 * Test class for DocContainerItem.
 * Generated by PHPUnit on 2012-07-16 at 11:14:40.
 */
class DocContainerItemTest extends PHPUnit_Framework_TestCase {

	/**
	 * @var DocContainerItem
	 */
	protected $object;

	/**
	 * Sets up the fixture, for example, opens a network connection.
	 * This method is called before a test is executed.
	 */
	protected function setUp() {
		$this->object = new DocContainerItem;
	}

	/**
	 * Tears down the fixture, for example, closes a network connection.
	 * This method is called after a test is executed.
	 */
	protected function tearDown() {
		
	}

	/**
	 * @todo Implement testDeleteDocs().
	 */
	public function testDeleteDocs() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetAllChild().
	 */
	public function testGetAllChild() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetFullInfoById().
	 */
	public function testGetFullInfoById() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetNameById().
	 */
	public function testGetNameById() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetIdList().
	 */
	public function testGetIdList() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

	/**
	 * @todo Implement testGetParentId().
	 */
	public function testGetParentId() {
		// Remove the following lines when you implement this test.
		$this->markTestIncomplete(
				'This test has not been implemented yet.'
		);
	}

}

?>
